/**
 * AgentRunBadge — provenance line on asset detail.
 * Why: G-01 governance trace visible in demo (doc 21).
 */

import type { ReactElement } from "react";

import type { AgentRunSummaryDTO } from "@preflight/schemas";

interface AgentRunBadgeProps {
  run: AgentRunSummaryDTO | null;
}

function formatModel(model: string): string {
  const parts = model.split(":");
  return parts.length > 1 ? (parts[1] ?? model) : model;
}

function formatLatency(ms: number): string {
  if (ms < 1000) {
    return `${ms}ms`;
  }

  return `${(ms / 1000).toFixed(2)}s`;
}

function formatTokens(run: AgentRunSummaryDTO): string | null {
  if (run.totalTokens !== null) {
    return `${run.totalTokens.toLocaleString()} tokens`;
  }

  if (run.inputTokens !== null && run.outputTokens !== null) {
    return `${(run.inputTokens + run.outputTokens).toLocaleString()} tokens`;
  }

  return null;
}

function formatCost(costUsd: number | null): string | null {
  if (costUsd === null || costUsd <= 0) {
    return null;
  }

  return `$${costUsd.toFixed(4)}`;
}

export function AgentRunBadge({ run }: AgentRunBadgeProps): ReactElement {
  if (run === null) {
    return (
      <p className="font-mono text-mono-faint text-fg-faint">
        Provenance: Seeded — no live generator run
      </p>
    );
  }

  const parts = [
    `Generated by ${formatModel(run.model)} v${run.agentDefVersion}`,
    formatLatency(run.latencyMs),
    formatTokens(run),
    formatCost(run.costUsd),
  ].filter((part): part is string => part !== null);

  if (!run.ok) {
    parts.push("run failed");
  }

  return (
    <p className="font-mono text-mono-faint text-fg-faint">
      Provenance: {parts.join(" · ")}
    </p>
  );
}
